// Bundles the FCM service worker (src/sw/firebase-messaging-sw.ts, modular Firebase SDK) into one
// classic script (Firefox has no module service workers) and writes it as a string for the
// /api/firebase-messaging-sw route. Runs before dev, build and typecheck (package.json pre-scripts);
// the output is generated, not committed.
import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';

const result = await build({
  entryPoints: ['src/sw/firebase-messaging-sw.ts'],
  bundle: true,
  format: 'iife',
  target: 'es2020',
  minify: true,
  legalComments: 'none',
  write: false,
  logLevel: 'warning',
});
const code = result.outputFiles[0].text;
writeFileSync(
  'src/app/api/firebase-messaging-sw/swBundle.generated.ts',
  `// Generated by scripts/build-sw.mjs from src/sw/firebase-messaging-sw.ts. Do not edit.\nexport const SW_SOURCE = ${JSON.stringify(code)};\n`,
);
console.log(`build-sw: ${(code.length / 1024).toFixed(1)} KiB`);
